-- SCRIPT DE CONFIGURAÇÃO DE TABELAS DO SUPABASE - BAR DO RICARDO
-- Copie e cole este script no SQL Editor do seu projeto Supabase e clique em RUN.

-- NOTA PARA PROJETOS EXISTENTES: Se você já rodou este script antes, rode apenas as linhas abaixo no SQL Editor do Supabase:
-- ALTER TABLE customers ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
-- ALTER TABLE products ADD COLUMN IF NOT EXISTS components JSONB DEFAULT '[]';
-- ALTER TABLE products ADD COLUMN IF NOT EXISTS "parentProductId" INT REFERENCES products(id) ON DELETE SET NULL;
-- ALTER TABLE products ADD COLUMN IF NOT EXISTS "conversionFactor" INT DEFAULT 1;
-- ALTER TABLE products ADD COLUMN IF NOT EXISTS "unitsInOpen" INT DEFAULT 0;

-- 1. Tabela de Categorias
CREATE TABLE IF NOT EXISTS categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT,
  icon TEXT
);

-- 2. Tabela de Produtos
CREATE TABLE IF NOT EXISTS products (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryId" INT REFERENCES categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  cost NUMERIC,
  stock INT DEFAULT 0,
  "minStock" INT DEFAULT 0,
  unit TEXT,
  active BOOLEAN DEFAULT TRUE,
  components JSONB DEFAULT '[]',
  "parentProductId" INT REFERENCES products(id) ON DELETE SET NULL,
  "conversionFactor" INT DEFAULT 1,
  "unitsInOpen" INT DEFAULT 0
);

-- 3. Tabela de Mesas/Comandas
CREATE TABLE IF NOT EXISTS tables (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number INT,
  capacity INT,
  status TEXT DEFAULT 'free',
  label TEXT,
  type TEXT DEFAULT 'table'
);

-- 4. Tabela de Pedidos/Contas em Aberto
CREATE TABLE IF NOT EXISTS orders (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tableId" INT REFERENCES tables(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'open',
  "customerName" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  discount NUMERIC DEFAULT 0,
  "discountType" TEXT DEFAULT 'percent'
);

-- 5. Tabela de Itens de Pedidos
CREATE TABLE IF NOT EXISTS order_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" INT REFERENCES orders(id) ON DELETE CASCADE,
  "productId" INT REFERENCES products(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  qty INT DEFAULT 1,
  note TEXT
);

-- 6. Tabela de Vendas Finalizadas
CREATE TABLE IF NOT EXISTS sales (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" INT,
  "tableId" INT,
  "tableName" TEXT,
  total NUMERIC NOT NULL,
  discount NUMERIC DEFAULT 0,
  "paymentMethod" TEXT,
  "sellerId" INT,
  "sellerName" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  payments JSONB
);

-- 7. Tabela de Itens das Vendas Finalizadas
CREATE TABLE IF NOT EXISTS sale_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "saleId" INT REFERENCES sales(id) ON DELETE CASCADE,
  "productId" INT,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  qty INT DEFAULT 1
);

-- 8. Tabela de Movimentações de Estoque
CREATE TABLE IF NOT EXISTS stock_movements (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" INT REFERENCES products(id) ON DELETE CASCADE,
  date TIMESTAMPTZ DEFAULT NOW(),
  qty INT NOT NULL,
  type TEXT NOT NULL,
  reason TEXT
);

-- 9. Tabela de Sessões de Caixa
CREATE TABLE IF NOT EXISTS cash_sessions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL,
  "openedAt" TIMESTAMPTZ DEFAULT NOW(),
  "closedAt" TIMESTAMPTZ,
  "openedBy" TEXT,
  "closedBy" TEXT,
  "initialCash" NUMERIC NOT NULL,
  "finalCash" NUMERIC,
  "totalSales" NUMERIC,
  difference NUMERIC,
  notes TEXT
);

-- 10. Tabela de Configurações do Sistema
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB
);

-- 11. Tabela de Clientes Cadastrados
CREATE TABLE IF NOT EXISTS customers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  notes TEXT,
  active BOOLEAN DEFAULT TRUE,
  "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Tabela de Registros de Fiado
CREATE TABLE IF NOT EXISTS fiado (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerId" INT REFERENCES customers(id) ON DELETE CASCADE,
  "customerName" TEXT,
  "saleId" INT,
  amount NUMERIC NOT NULL,
  date TIMESTAMPTZ DEFAULT NOW(),
  paid BOOLEAN DEFAULT FALSE
);

-- 13. Tabela de Usuários/Funcionários
CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Desabilitar RLS (Row Level Security) para permitir leitura/escrita direta pelo app cliente
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE tables DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE fiado DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;

